# Start the testnet server with the command 'docker-compose up -d'

token-liquidity-mongodb:
  image: mongo
  ports:
    - "3500:27017" # <host port>:<container port>
  volumes:
    - ./database:/data/db
  command: mongod --smallfiles --logpath=/dev/null # -- quiet
  restart: always

token-liquidity-testnet:
  build: .
  dockerfile: testnet/Dockerfile
  links:
    - token-liquidity-mongodb
  ports:
    - "5100:5100" # <host port>:<container port>
  volumes:
    - ./testnet/logs:/home/token/token-liquidity/logs
    - ./testnet/state:/home/token/token-liquidity/state
#    - ./keys:/home/coinjoin/consolidating-coinjoin/keys

  restart: always
